# Generated by Django 5.1.5 on 2025-01-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporteur', models.CharField(max_length=100)),
                ('nombre_palettes', models.IntegerField()),
                ('reserve', models.BooleanField(default=False)),
                ('numero_commande', models.CharField(max_length=50)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField()),
            ],
        ),
    ]
