# Generated by Django 5.1.5 on 2025-01-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
