# Generated by Django 5.1.5 on 2025-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_alter_livraison_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='signature',
        ),
        migrations.AddField(
            model_name='livraison',
            name='nom_employe',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='nom_transporteur',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='signature_employe',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livraison',
            name='signature_transporteur',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livraison',
            name='numero_commande',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='transporteur',
            field=models.CharField(max_length=255),
        ),
    ]
