# Generated by Django 5.1.5 on 2025-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_rename_nom_transporteur_livraison_nom_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='signature_chauffeur',
            field=models.ImageField(upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='signature_employe',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
