# Generated by Django 5.1.5 on 2025-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0005_alter_livraison_signature_chauffeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='type_operation',
            field=models.CharField(choices=[('delivery', 'Livraison'), ('expedition', 'Expédition')], default='delivery', max_length=20),
        ),
    ]
