# Generated by Django 5.1.5 on 2025-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0006_livraison_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='recordDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
